In [1]:
from __future__ import print_function
import torch

In [2]:
x=torch.empty(5,3)
print(x)

tensor([[ 0.0000e+00, -8.5899e+09, -2.9331e-27],
        [ 2.0005e+00,  1.1210e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [3]:
x=torch.rand(5,3)

In [4]:
print(x)

tensor([[0.5961, 0.5284, 0.2400],
        [0.4772, 0.9361, 0.5371],
        [0.7582, 0.8475, 0.1482],
        [0.9765, 0.8769, 0.2263],
        [0.2854, 0.6779, 0.5631]])


In [6]:
#construct a matirx filled zeros and of dtype long:
x= torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x=torch.tensor([5.5,3])

In [8]:
print(x)

tensor([5.5000, 3.0000])


In [9]:
x=x.new_ones(5,3,dtype=torch.double)
print(x)
x=torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.3264,  1.4848, -0.4092],
        [-0.8601, -1.1436, -0.7888],
        [ 0.3235, -0.5149, -0.4107],
        [ 0.0060, -1.1171,  0.8428],
        [-0.6839,  1.6500, -0.2026]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
y=torch.rand(5,3)
print(x+y)

tensor([[-0.2060,  2.0706, -0.2952],
        [ 0.0667, -0.9557, -0.1099],
        [ 0.5328,  0.2337,  0.2445],
        [ 0.7216, -0.6038,  1.8359],
        [-0.6067,  1.7446,  0.5502]])


In [12]:
print(torch.add(x,y))

tensor([[-0.2060,  2.0706, -0.2952],
        [ 0.0667, -0.9557, -0.1099],
        [ 0.5328,  0.2337,  0.2445],
        [ 0.7216, -0.6038,  1.8359],
        [-0.6067,  1.7446,  0.5502]])


In [13]:
x=torch.ones(5,3)

In [14]:
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [17]:
result=torch.empty(5,3)
torch.add(x,y,out=result)

tensor([[1.0190, 1.1083, 0.3218],
        [1.4863, 0.2374, 1.5237],
        [0.4937, 1.7366, 1.3766],
        [1.5136, 0.6157, 1.8539],
        [0.5281, 0.4435, 1.7010]])

In [18]:
#adds x to y
y.add_(x)
print(y)

tensor([[1.0190, 1.1083, 0.3218],
        [1.4863, 0.2374, 1.5237],
        [0.4937, 1.7366, 1.3766],
        [1.5136, 0.6157, 1.8539],
        [0.5281, 0.4435, 1.7010]])


In [19]:
print(x[:1])

tensor([[0.8985, 0.5224, 0.2078]])


In [20]:
#Resizing: if you want to resize/reshape tensor, you can use "torch.view"
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)#the size -1 is inferred from other dimension 
print(x.size(), y.size(), z.size())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [22]:
#if you have a one element tensor, use .item() to get the value as a python number
x=torch.randn(1)
print(x)
print(x.item())

tensor([-0.8454])
-0.8454270958900452


In [23]:
#Numpy Bridge
#converting a Torch Tensor to a NumPy array and vice versa is a breeze.

#The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

In [24]:
a=torch.ones(5)

In [25]:
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [27]:
a.add_(1)
print(a)
print(b)#b도 바뀜.

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
#converting numpy array to torch tensor
import numpy as np 
a=np.ones(5)
b=torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
